TerraCottaStore/Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TerraCottaStore.Models;
using TerraCottaStore.Repository;

namespace TerraCottaStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin,Author")]
    public class BrandController : Controller
    {
        private readonly DataContext _datacontext;

        public BrandController(DataContext dataContext ) 
        {
         _datacontext = dataContext;
        }

        /*public async Task <IActionResult> Index()
        {
            return View(await _datacontext.Brands.OrderByDescending(p => p.Id).ToListAsync());
        }*/
        public async Task<IActionResult> Index(int pg = 1)
        {   var list = await _datacontext.Brands.ToListAsync();
            const int pageSize = 10; //10 items/trang

            if (pg < 1) //page < 1;
            {
                pg = 1; //page ==1
            }
            int recsCount = list.Count();

            var pager = new Paginate(recsCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;

            var data = list.Skip(recSkip).Take(pager.PageSize).ToList();

            ViewBag.Pager = pager;

            return View(data);
            
        }

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BrandModel brand)
        {

            if (ModelState.IsValid)
            {
                brand.slug = brand.Name.Replace(" ", "-");
                var Slug = await _datacontext.Brands.FirstOrDefaultAsync(x => x.slug == brand.slug);
                if (Slug != null)
                {
                    ModelState.AddModelError("", "Danh mục đã có trong hệ thống");
                    return View(brand);
                }


                _datacontext.AddAsync(brand);
                await _datacontext.SaveChangesAsync();

                TempData["success"] = "add successfully!";
                return RedirectToAction("Index");

            }
            else
            {
                TempData["error"] = "Got some error in model     !";
                List<string> errors = new List<string>();
                foreach (var value in ModelState.Values)
                    foreach (var error in value.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                string errormessage = string.Join("\n", errors);
                return BadRequest(errormessage);
            }


            return View(brand);
        }
        public async Task<IActionResult> delete(int id)
        {
            BrandModel brand = await _datacontext.Brands.FindAsync(id);


            _datacontext.Brands.Remove(brand);
            await _datacontext.SaveChangesAsync();
            TempData["error"] = "Delete suceesful!";

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int id)
        {
            BrandModel brand = await _datacontext.Brands.FindAsync(id);
            return View(brand);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BrandModel brand)
        {

            if (ModelState.IsValid)
            {
                brand.slug = brand.Name.Replace(" ", "-");
                var Slug = await _datacontext.Brands.FirstOrDefaultAsync(x => x.slug == brand.slug);
                if (Slug != null)
                {
                    ModelState.AddModelError("", "Danh mục đã có trong hệ thống");
                    return View(brand);
                }


                _datacontext.Update(brand);
                await _datacontext.SaveChangesAsync();

                TempData["success"] = "add successfully!";
                return RedirectToAction("Index");

            }
            else
            {
                TempData["error"] = "Got some error in model     !";
                List<string> errors = new List<string>();
                foreach (var value in ModelState.Values)
                    foreach (var error in value.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                string errormessage = string.Join("\n", errors);
                return BadRequest(errormessage);
            }


            return View(brand);
        }
        public async Task<IActionResult> Shutdown(int id)
        {
            BrandModel brand = await _datacontext.Brands.FindAsync(id);


            brand.status = 0;
            _datacontext.Brands.Update(brand);
            await _datacontext.SaveChangesAsync();
            TempData["error"] = "Setoff suceesful!";

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Turnon(int id)
        {
            BrandModel brand = await _datacontext.Brands.FindAsync(id);


            brand.status = 1;
            _datacontext.Brands.Update(brand);
            await _datacontext.SaveChangesAsync();
            TempData["success"] = "turn on suceesful!";

            return RedirectToAction("Index");
        }
    }
}

TerraCottaStore/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TerraCottaStore.Models;
using TerraCottaStore.Repository;

namespace TerraCottaStore.Controllers
{
	public class BrandController : Controller
	{
		private readonly DataContext _datacontext;

		public BrandController(DataContext dataContext) 
		{
		 _datacontext = dataContext;
		}

		public async Task<IActionResult> Index(string Slug = "")
		{
			BrandModel brand = _datacontext.Brands.Where(c => c.slug == Slug).FirstOrDefault();
			if (brand == null)
			{
				return RedirectToAction("Index");
			}

			var productByBrand = _datacontext.Products.Where(c => c.CategoryID == brand.Id);

			return View(await productByBrand.OrderByDescending(C => C.Id).ToListAsync());
		}
	}
}

TerraCottaStore/Areas/Admin/Views/Brand/Create.cshtml
@model BrandModel
@{
    ViewData["title"] = "Create brand";
}
<h4>New Brand info</h4>
<div class="col-md-9">


    <form asp-action="Create" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label> Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger" />

        </div>

        <div class="form-group">
            <label>Description</label>

            <textarea asp-for="Description" class="form-control"> </textarea>

            <span asp-validation-for="Description" class="text-danger" />

        </div>
        <div class="form-group">
            <label>Status</label>
            <select asp-for="status" class="form-control">
                <option value="1">Hiển thị</option>
                <option value="0">Ẩn</option>
            </select>
            <span asp-validation-for="status" class="text-danger" />
        </div>

        <div class="form-group">
            <button class="btn btn-primary"> Create </button>

        </div>
    </form>
    <a asp-action="Index"> Back to category !</a>
</div>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Description')
    </script>
}

TerraCottaStore/Areas/Admin/Views/Brand/Edit.cshtml
@model BrandModel
@{
    ViewData["title"] = "edit brand";
}
<h4>edit Brand info</h4>
<div class="col-md-9">


    <form asp-action="Edit" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label> Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger" />

        </div>

        <div class="form-group">
            <label>Description</label>

            <textarea asp-for="Description" class="form-control"> </textarea>

            <span asp-validation-for="Description" class="text-danger" />

        </div>
        <div class="form-group">
            <label>Status</label>
            <select asp-for="status" class="form-control">
                <option value="1">Hiển thị</option>
                <option value="0">Ẩn</option>
            </select>
            <span asp-validation-for="status" class="text-danger" />
        </div>

        <div class="form-group">
            <button class="btn btn-primary"> Update </button>

        </div>
    </form>
    <a asp-action="Index"> Back to brands !</a>
</div>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Description')
    </script>
}

TerraCottaStore/Areas/Admin/Views/Brand/Index.cshtml
@model IEnumerable<BrandModel>
@{
    ViewData["title"] = "Brand Listed";
    Paginate pager = new Paginate();
    int pageno = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageno = pager.CurrentPage;
    }
}
<h3>List Brand</h3>
<a asp-action="Create" asp-controller="Brand">Creat new Brand !</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Brand  Name</th>
            <th scope="col">Brand Desciption</th>
            <th scope="col">Slug</th>
            <th scope="col">Status</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <th scope="row">@item.Id</th>

                <td>@item.Name</td>
                <td>@Html.Raw(item.Description)</td>


                <td>@item.slug</td>

                @if (@item.status == 1)
                {
                    <td style="color:darkgreen">hiển thị</td>
                }
                else
                {
                    <td style="color:crimson">Ẩn</td>
                }
                <td>
                    <a class="btn btn-warning btn-sm" asp-action="Edit" asp-controller="Brand" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-danger btn-sm confirmDeletion" asp-action="delete" asp-controller="Brand" asp-route-id="@item.Id">Delete</a>

                    @if (item.status == 1)
                    {
                        <a class="btn btn-danger btn-sm" asp-action="Shutdown" asp-controller="Brand" asp-route-id="@item.Id">Set off</a>
                    }
                    else
                    {
                        <a class="btn btn-danger btn-sm" asp-action="Turnon" asp-controller="Brand" asp-route-id="@item.Id">Set on</a>

                    }

                </td>

            </tr>
        }
      

    </tbody>
</table>
<partial name="_Paging" model="@pager" />